---
# Usage: http://ruhoh.com/usage/configure/

RuhohSpec: '1.0'
theme : twitter
production_url : http://hugozhu.myalert.info

posts:
  permalink: /:year/:month/:day/:title.html
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'