title : Hugo Zhu
tagline: Programming Software Architecture Java Golang Raspberry Pi Web
author :
  name : Hugo Zhu
  email : hugozhu@gmail.com
  github : hugozhu
  twitter : hugozhu
  feedburner : hugozhu

navigation :
  - posts.md  
  - pages.html
  - archive.html
  - tags.html
  - categories.html
  - about.md
  